import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useContext, useEffect, useState } from 'react';
import { GlobalContext } from '../context';
import { Blog } from '../types';

const Home: NextPage = () => {
  const { blogs } = useContext(GlobalContext);

  const [pageData, setPageData] = useState<Blog[]>([]);

  useEffect(() => {
    setPageData(() => blogs.reverse());
  }, [blogs]);

  return (
    <div className="blogs-container">
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>All Blogs</h2>
      <div>
        {pageData.map((blog, index) => (
          <Link href={`/edit/${blog.slug}`} key={blog.slug}>
            <div className="blog-container">
              <div>
                <b>{blog.title}</b>
              </div>
              <div>{blog.description}</div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Home;
